TRANSLATIONS = {
    'en': {
        # Navbar
        'nav_home': 'Home',
        'nav_tools': 'Tools',
        'nav_analytics': 'Analytics',
        'nav_chatbot': 'AI Chatbot',
        'nav_history': 'History',
        'nav_about': 'About',
        'nav_new_assessment': 'New Assessment',
        'nav_logout': 'Logout',
        'nav_risk_assessment': 'Risk Assessment',
        'nav_insurance_quote': 'Insurance Quote',
        'nav_risk_comparison': 'Risk Comparison',

        # Footer
        'footer_quote': 'Quote Calculator',
        'footer_comparison': 'Comparison Tool',
        'footer_desc': 'Road Accident Risk Assessment System for Insurance Companies',
        'footer_copy': 'Pearson BTEC Level 6 Diploma in Digital Technologies • Unit 2: Independent Project • © 2025',

        # Login
        'login_title': 'Admin Portal — Please sign in',
        'login_email': 'Email',
        'login_password': 'Password',
        'login_remember': 'Remember me',
        'login_btn': 'Sign In',
        'login_invalid': 'Invalid username or password.',

        # Home
        'home_hero_title': 'Road Accident Risk Assessment',
        'home_hero_sub': 'for Insurance Companies',
        'home_hero_desc': 'A machine learning platform that evaluates driver risk profiles, predicts claim probabilities and calculates premium multipliers.',
        'home_btn_assessment': 'Start Assessment',
        'home_btn_analytics': 'View Analytics',
        'home_total': 'Total Records',
        'home_accuracy': 'ML Accuracy',
        'home_categories': 'Risk Categories',
        'home_recent': 'Recent Assessments',
        'home_view_all': 'View All',

        # Assessment
        'assessment_title': 'Risk Assessment Form',
        'assessment_sub': 'Complete all 3 sections to receive your personalised risk score and premium recommendation.',
        'assessment_step1': 'Driver Profile',
        'assessment_step2': 'Vehicle & Location',
        'assessment_step3': 'Driving History',
        'assessment_live': 'LIVE ESTIMATE',
        'assessment_next': 'Next',
        'assessment_back': 'Back',
        'assessment_submit': 'Submit Assessment',
        'assessment_driver_age': 'Driver Age',
        'assessment_experience': 'Driving Experience (yrs)',
        'assessment_gender': 'Gender',
        'assessment_marital': 'Marital Status',
        'assessment_credit': 'Credit Score',
        'assessment_vehicle_type': 'Vehicle Type',
        'assessment_vehicle_age': 'Vehicle Age (yrs)',
        'assessment_mileage': 'Annual Mileage (miles)',
        'assessment_location': 'Primary Location',
        'assessment_accidents': 'Previous Accidents (3yrs)',
        'assessment_violations': 'Traffic Violations (3yrs)',
        'assessment_night': 'Night Driving %',

        # History
        'history_title': 'Assessment History',
        'history_sub': 'All previously submitted risk assessments',
        'history_export': 'Export CSV',
        'history_search': 'Search vehicle type, location, gender…',
        'history_filter': 'Filter:',
        'history_total': 'Total Records',
        'history_avg': 'Avg Score (Page)',
        'history_highest': 'Highest Score',
        'history_lowest': 'Lowest Score',
        'history_col_date': 'Date',
        'history_col_age': 'Age',
        'history_col_vehicle': 'Vehicle',
        'history_col_location': 'Location',
        'history_col_accidents': 'Accidents',
        'history_col_score': 'Risk Score',
        'history_col_category': 'Category',
        'history_col_premium': 'Premium ×',
        'history_col_status': 'Status',
        'history_col_actions': 'Actions',
        'history_no_data': 'No assessments yet',
        'history_start': 'Start Assessment',
        'history_delete_confirm': 'Delete selected?',

        # Status
        'status_pending': '⏳ Pending',
        'status_reviewed': '🔍 Reviewed',
        'status_approved': '✅ Approved',

        # Report
        'report_title': 'Assessment Report',
        'report_back': 'Back',
        'report_print': 'Print',
        'report_pdf': 'PDF',
        'report_quote': 'Get Quote',
        'report_new': 'New Assessment',
        'report_driver': 'Driver Profile',
        'report_vehicle': 'Vehicle & Location',
        'report_behaviour': 'Driving History & Behaviour',
        'report_recommendations': 'Personalised Recommendations',
        'report_age': 'Age',
        'report_experience': 'Experience',
        'report_gender': 'Gender',
        'report_marital': 'Marital Status',
        'report_credit': 'Credit Score',
        'report_vehicle_type': 'Vehicle Type',
        'report_vehicle_age': 'Vehicle Age',
        'report_mileage': 'Annual Mileage',
        'report_location': 'Primary Location',
        'report_premium': 'Premium Multiplier',
        'report_claim': 'Claim Probability',
        'report_prior_acc': 'Prior Accidents',
        'report_accidents': 'Accidents (3yr)',
        'report_violations': 'Violations (3yr)',
        'report_night': 'Night Driving',
        'report_miles': 'Annual Miles',
        'report_history': 'History',
        'report_ask_ai': 'Ask AI',
        'report_compare': 'Compare',

        # Dashboard
        'dashboard_title': 'Analytics Dashboard',
        'dashboard_sub': 'Real-time performance, risk metrics and assessment trends.',
        'dashboard_export': 'Export CSV',
        'dashboard_refresh': 'Refresh',

        # Notes modal
        'notes_title': 'Admin Notes',
        'notes_placeholder': 'Write a note...',
        'notes_cancel': 'Cancel',
        'notes_save': 'Save',

        # Delete modal
        'delete_title': 'Delete',
        'delete_confirm': 'Are you sure you want to delete',
        'delete_no': 'No',
        'delete_yes': 'Yes, delete',

        # Index / Hero
        'hero_badge': 'AI-Powered Risk Engine · ML Accuracy: 86%+',
        'hero_title1': 'Road Accident',
        'hero_title2': 'Risk Assessment',
        'hero_title3': 'for Insurance Companies',
        'hero_desc': 'A machine-learning platform that evaluates driver risk profiles, predicts claim probabilities and calculates premium multipliers — delivering instant, data-driven underwriting decisions.',
        'hero_ask_ai': 'Ask AI',
        'stat_training': 'Training Records',
        'stat_accuracy': 'Model Accuracy',
        'stat_categories': 'Risk Categories',
        'stat_features': 'Input Features',
        'stat_low': 'Low Risk',
        'stat_medium': 'Medium Risk',
        'stat_high': 'High Risk',
        'stat_very_high': 'Very High Risk',
        'stat_total': 'Total assessments recorded:',
        'stat_view_all': 'View all',
        'feat_title': 'Everything You Need for Intelligent Underwriting',
        'feat_sub': 'Data-driven tools built for modern insurance professionals',
        'feat_badge': 'System Capabilities',
        'feat_ml_title': 'ML Risk Engine',
        'feat_ml_desc': 'Gradient Boosting Classifier trained on 12,000 records, compared against 4 algorithms with 5-fold cross-validation.',
        'feat_ml_btn': 'View Metrics',
        'feat_assess_title': 'Risk Assessment',
        'feat_assess_desc': '3-section guided form with live risk preview. Get risk score (0–100), premium multiplier and factor contribution chart instantly.',
        'feat_assess_btn': 'Start Now',
        'feat_quote_title': 'Quote Calculator',
        'feat_quote_desc': 'Enter any base premium and get a full quote breakdown across 3 coverage tiers with savings recommendations.',
        'feat_quote_btn': 'Calculate',
        'feat_chat_title': 'AI Chatbot',
        'feat_chat_desc': 'Advanced NLP chatbot with deep insurance domain knowledge. Answers any query about risk, premiums, fraud, telematics and more — available 24/7.',
        'feat_chat_btn': 'Chat Now',
        'feat_dash_title': 'Analytics Dashboard',
        'feat_dash_desc': '8 interactive Chart.js charts: risk distribution, feature importance, age histogram, score distribution, model comparison and more.',
        'feat_dash_btn': 'Dashboard',
        'feat_compare_title': 'Risk Comparison',
        'feat_compare_desc': 'Side-by-side comparison of two driver profiles with head-to-head charts and factor-level winner indicators.',
        'feat_compare_btn': 'Compare',
        'feat_report_title': 'Full Reports',
        'feat_report_desc': 'Print-ready & PDF assessment reports with risk gauge, factor charts, premium breakdown and personalised recommendations.',
        'feat_report_btn': 'View History',
        'feat_csv_title': 'CSV Export',
        'feat_csv_desc': 'Export all assessment history to CSV for offline analysis, reporting, or integration with third-party insurance systems.',
        'feat_csv_btn': 'Export',
        'how_title': 'How It Works',
        'how_sub': 'Four steps from input to actionable insurance insight',
        'how_step1_title': 'Input Profile',
        'how_step1_desc': 'Enter driver demographics, vehicle details and driving behaviour data.',
        'how_step2_title': 'Feature Processing',
        'how_step2_desc': 'Data is normalised and one-hot encoded by the scikit-learn pipeline.',
        'how_step3_title': 'Model Prediction',
        'how_step3_desc': 'Gradient Boosting classifies risk into 4 categories with probability scores.',
        'how_step4_title': 'Report & Advice',
        'how_step4_desc': 'Full report with risk gauge, factor chart, premium multiplier and tips.',
        'recent_title': 'Recent Assessments',
        'recent_view_all': 'View All',
        'tbl_id': 'ID', 'tbl_date': 'Date', 'tbl_age': 'Age',
        'tbl_vehicle': 'Vehicle', 'tbl_score': 'Risk Score',
        'tbl_cat': 'Category', 'tbl_premium': 'Premium ×',

        # Common
        'years': 'years',
        'miles': 'miles',
        'good': 'Good',
        'fair': 'Fair',
        'poor': 'Poor',
        'low': 'Low',
        'medium': 'Medium',
        'high': 'High',
        'very_high': 'Very High',
        'all': 'All',
    },

    'uz': {
        # Navbar
        'nav_home': 'Bosh sahifa',
        'nav_tools': 'Vositalar',
        'nav_analytics': 'Tahlil',
        'nav_chatbot': 'AI Chatbot',
        'nav_history': 'Tarix',
        'nav_about': 'Haqida',
        'nav_new_assessment': 'Yangi baholash',
        'nav_logout': 'Chiqish',
        'nav_risk_assessment': 'Risk baholash',
        'nav_insurance_quote': 'Sug\'urta narxi',
        'nav_risk_comparison': 'Risk taqqoslash',

        # Footer
        'footer_quote': 'Narx kalkulyatori',
        'footer_comparison': 'Taqqoslash vositasi',
        'footer_desc': 'Sug\'urta kompaniyalari uchun yo\'l transport hodisalari risk baholash tizimi',
        'footer_copy': 'Pearson BTEC Level 6 Diploma in Digital Technologies • Unit 2: Mustaqil loyiha • © 2025',

        # Login
        'login_title': 'Admin portali — Iltimos, kiring',
        'login_email': 'Elektron pochta',
        'login_password': 'Parol',
        'login_remember': 'Meni eslab qol',
        'login_btn': 'Kirish',
        'login_invalid': 'Noto\'g\'ri foydalanuvchi nomi yoki parol.',

        # Home
        'home_hero_title': 'Yo\'l Transport Hodisalari Risk Baholash',
        'home_hero_sub': 'Sug\'urta kompaniyalari uchun',
        'home_hero_desc': 'Haydovchi risk profillarini baholaydigan, da\'vo ehtimolini bashorat qiladigan va premium multiplikatorlarni hisoblaydigan machine learning platforma.',
        'home_btn_assessment': 'Baholashni boshlash',
        'home_btn_analytics': 'Tahlilni ko\'rish',
        'home_total': 'Jami yozuvlar',
        'home_accuracy': 'ML aniqligi',
        'home_categories': 'Risk kategoriyalari',
        'home_recent': 'So\'nggi baholashlar',
        'home_view_all': 'Barchasini ko\'rish',

        # Assessment
        'assessment_title': 'Risk Baholash Formasi',
        'assessment_sub': 'Shaxsiy risk balingiz va premium tavsiyangizni olish uchun 3 bo\'limni to\'ldiring.',
        'assessment_step1': 'Haydovchi profili',
        'assessment_step2': 'Avtomobil va joylashuv',
        'assessment_step3': 'Haydovchilik tarixi',
        'assessment_live': 'JONLI BAHOLASH',
        'assessment_next': 'Keyingisi',
        'assessment_back': 'Orqaga',
        'assessment_submit': 'Baholashni yuborish',
        'assessment_driver_age': 'Haydovchi yoshi',
        'assessment_experience': 'Haydovchilik tajribasi (yil)',
        'assessment_gender': 'Jins',
        'assessment_marital': 'Oilaviy holat',
        'assessment_credit': 'Kredit bali',
        'assessment_vehicle_type': 'Avtomobil turi',
        'assessment_vehicle_age': 'Avtomobil yoshi (yil)',
        'assessment_mileage': 'Yillik masofa (mil)',
        'assessment_location': 'Asosiy joylashuv',
        'assessment_accidents': 'Oldingi hodisalar (3 yil)',
        'assessment_violations': 'Yo\'l harakati qoidalari buzilishi (3 yil)',
        'assessment_night': 'Tungi haydovchilik %',

        # History
        'history_title': 'Baholashlar tarixi',
        'history_sub': 'Barcha ilgari yuborilgan risk baholashlar',
        'history_export': 'CSV yuklash',
        'history_search': 'Avtomobil turi, joylashuv, jins bo\'yicha qidirish…',
        'history_filter': 'Filter:',
        'history_total': 'Jami yozuvlar',
        'history_avg': 'O\'rtacha ball (sahifa)',
        'history_highest': 'Eng yuqori ball',
        'history_lowest': 'Eng past ball',
        'history_col_date': 'Sana',
        'history_col_age': 'Yosh',
        'history_col_vehicle': 'Avtomobil',
        'history_col_location': 'Joylashuv',
        'history_col_accidents': 'Hodisalar',
        'history_col_score': 'Risk bali',
        'history_col_category': 'Kategoriya',
        'history_col_premium': 'Premium ×',
        'history_col_status': 'Holat',
        'history_col_actions': 'Amallar',
        'history_no_data': 'Hali baholashlar yo\'q',
        'history_start': 'Baholashni boshlash',
        'history_delete_confirm': 'Tanlanganlarni o\'chirasizmi?',

        # Status
        'status_pending': '⏳ Kutilmoqda',
        'status_reviewed': '🔍 Ko\'rib chiqildi',
        'status_approved': '✅ Tasdiqlandi',

        # Report
        'report_title': 'Baholash hisoboti',
        'report_back': 'Orqaga',
        'report_print': 'Chop etish',
        'report_pdf': 'PDF',
        'report_quote': 'Narx olish',
        'report_new': 'Yangi baholash',
        'report_driver': 'Haydovchi profili',
        'report_vehicle': 'Avtomobil va joylashuv',
        'report_behaviour': 'Haydovchilik tarixi va xulq-atvori',
        'report_recommendations': 'Shaxsiy tavsiyalar',
        'report_age': 'Yosh',
        'report_experience': 'Tajriba',
        'report_gender': 'Jins',
        'report_marital': 'Oilaviy holat',
        'report_credit': 'Kredit bali',
        'report_vehicle_type': 'Avtomobil turi',
        'report_vehicle_age': 'Avtomobil yoshi',
        'report_mileage': 'Yillik masofa',
        'report_location': 'Asosiy joylashuv',
        'report_premium': 'Premium multiplikatori',
        'report_claim': 'Da\'vo ehtimoli',
        'report_prior_acc': 'Oldingi hodisalar',
        'report_accidents': 'Hodisalar (3 yil)',
        'report_violations': 'Qoidabuzarliklar (3 yil)',
        'report_night': 'Tungi haydovchilik',
        'report_miles': 'Yillik millar',
        'report_history': 'Tarix',
        'report_ask_ai': 'AI dan so\'rash',
        'report_compare': 'Taqqoslash',

        # Dashboard
        'dashboard_title': 'Tahlil paneli',
        'dashboard_sub': 'Real vaqt ko\'rsatkichlari, risk metrikalari va baholash tendensiyalari.',
        'dashboard_export': 'CSV yuklash',
        'dashboard_refresh': 'Yangilash',

        # Notes modal
        'notes_title': 'Admin izohi',
        'notes_placeholder': 'Izoh yozing...',
        'notes_cancel': 'Bekor qilish',
        'notes_save': 'Saqlash',

        # Delete modal
        'delete_title': 'O\'chirish',
        'delete_confirm': 'Haqiqatan ham o\'chirmoqchimisiz',
        'delete_no': 'Yo\'q',
        'delete_yes': 'Ha, o\'chir',

        # Index / Hero
        'hero_badge': 'AI-Powered Risk Engine · ML aniqligi: 86%+',
        'hero_title1': 'Yo\'l Transport Hodisalari',
        'hero_title2': 'Risk Baholash',
        'hero_title3': 'Sug\'urta Kompaniyalari uchun',
        'hero_desc': 'Haydovchi risk profillarini baholaydigan, da\'vo ehtimolini bashorat qiladigan va premium multiplikatorlarni hisoblaydigan machine learning platforma.',
        'hero_ask_ai': 'AI dan so\'rash',
        'stat_training': 'O\'qitish yozuvlari',
        'stat_accuracy': 'Model aniqligi',
        'stat_categories': 'Risk kategoriyalari',
        'stat_features': 'Kirish xususiyatlari',
        'stat_low': 'Past risk',
        'stat_medium': 'O\'rta risk',
        'stat_high': 'Yuqori risk',
        'stat_very_high': 'Juda yuqori risk',
        'stat_total': 'Jami baholashlar:',
        'stat_view_all': 'Barchasini ko\'rish',
        'feat_title': 'Intellektual sug\'urta uchun kerakli hamma narsa',
        'feat_sub': 'Zamonaviy sug\'urta mutaxassislari uchun ma\'lumotga asoslangan vositalar',
        'feat_badge': 'Tizim imkoniyatlari',
        'feat_ml_title': 'ML Risk Mexanizmi',
        'feat_ml_desc': '12,000 yozuvda o\'qitilgan Gradient Boosting klassifikatori, 5-karra kross-validatsiya bilan 4 algoritm bilan taqqoslangan.',
        'feat_ml_btn': 'Ko\'rsatkichlarni ko\'rish',
        'feat_assess_title': 'Risk Baholash',
        'feat_assess_desc': 'Jonli risk oldindan ko\'rish bilan 3 bo\'limli forma. Risk bali (0–100), premium multiplikatori va omil hissasi jadvalini darhol oling.',
        'feat_assess_btn': 'Hozir boshlash',
        'feat_quote_title': 'Narx Kalkulyatori',
        'feat_quote_desc': 'Istalgan asosiy premiumni kiriting va tejash tavsiyalari bilan 3 ta qoplash darajasida to\'liq narx hisobini oling.',
        'feat_quote_btn': 'Hisoblash',
        'feat_chat_title': 'AI Chatbot',
        'feat_chat_desc': 'Chuqur sug\'urta bilimiga ega ilg\'or NLP chatbot. Risk, premiumlar, firibgarlik, telematika haqida istalgan savolga 24/7 javob beradi.',
        'feat_chat_btn': 'Chat boshlash',
        'feat_dash_title': 'Tahlil Paneli',
        'feat_dash_desc': '8 ta interaktiv Chart.js grafigi: risk taqsimoti, xususiyat ahamiyati, yosh gistogrammasi, ball taqsimoti va boshqalar.',
        'feat_dash_btn': 'Panel',
        'feat_compare_title': 'Risk Taqqoslash',
        'feat_compare_desc': 'Ikkita haydovchi profilini yon-yoniga taqqoslash, omil darajasidagi g\'olib ko\'rsatkichlari bilan.',
        'feat_compare_btn': 'Taqqoslash',
        'feat_report_title': 'To\'liq Hisobotlar',
        'feat_report_desc': 'Chop etish va PDF uchun tayyor baholash hisobotlari — risk o\'lchagich, omil jadvali, premium hisobi va tavsiyalar.',
        'feat_report_btn': 'Tarixni ko\'rish',
        'feat_csv_title': 'CSV Eksport',
        'feat_csv_desc': 'Barcha baholash tarixini CSV formatida yuklab oling — offline tahlil, hisobot yoki uchinchi tomon tizimlariga integratsiya uchun.',
        'feat_csv_btn': 'Eksport',
        'how_title': 'Qanday Ishlaydi',
        'how_sub': 'Kirishdan amaliy sug\'urta fikrigacha to\'rt qadam',
        'how_step1_title': 'Profil Kiritish',
        'how_step1_desc': 'Haydovchi demografiyasi, avtomobil ma\'lumotlari va haydovchilik xulq-atvori ma\'lumotlarini kiriting.',
        'how_step2_title': 'Xususiyat Qayta Ishlash',
        'how_step2_desc': 'Ma\'lumotlar scikit-learn pipeline orqali normallanadi va one-hot kodlanadi.',
        'how_step3_title': 'Model Bashorati',
        'how_step3_desc': 'Gradient Boosting riskni ehtimollik ballari bilan 4 toifaga tasniflaydi.',
        'how_step4_title': 'Hisobot va Maslahat',
        'how_step4_desc': 'Risk o\'lchagich, omil jadvali, premium multiplikatori va maslahatlar bilan to\'liq hisobot.',
        'recent_title': 'So\'nggi Baholashlar',
        'recent_view_all': 'Barchasini ko\'rish',
        'tbl_id': 'ID', 'tbl_date': 'Sana', 'tbl_age': 'Yosh',
        'tbl_vehicle': 'Avtomobil', 'tbl_score': 'Risk bali',
        'tbl_cat': 'Kategoriya', 'tbl_premium': 'Premium ×',

        # Common
        'years': 'yil',
        'miles': 'mil',
        'good': 'Yaxshi',
        'fair': 'O\'rtacha',
        'poor': 'Yomon',
        'low': 'Past',
        'medium': 'O\'rta',
        'high': 'Yuqori',
        'very_high': 'Juda yuqori',
        'all': 'Barchasi',
    }
}


def get_lang(session):
    return session.get('lang', 'en')


def t(session, key):
    lang = get_lang(session)
    return TRANSLATIONS.get(lang, TRANSLATIONS['en']).get(key, key)
